version: "3.9"
services:
    cash_accounting-backend:
        build: /root/ultra/cashAccounting-backend
        restart: always
        ports: 
            - "5001:5001"
        env_file:
            - /root/ultra/cashAccounting-backend/.env
        depends_on:
            - mongodb
        volumes:
            - /root/ultra/cashAccounting-backend/log:/app/log
    mongodb:
        image: mongo
        restart: always
        volumes:
            - mongovol:/data/db
        ports:
            - 27017:27017
        env_file:
            - ./.env
volumes:
    mongovol:
        external: true


